[tasks.objcopy]
command = "cargo"
args= [
    "objcopy",
    "--bin", "ant-auxiliary",
    "--release",
    "--",
    "-O", "binary",
    "target/thumbv7m-none-eabi/release/ant-auxiliary.bin"
]

[tasks.dfu]
command = "dfu-util"
args = [
    "-d", "0483:df11",
    "-a", "0",
    "-s", "0x08000000:leave",
    "-D", "target/thumbv7m-none-eabi/release/ant-auxiliary.bin"
]
dependencies = ["objcopy"]

[tasks.flash]
command = "st-flash"
args = [
    "write"
    "target/thumbv7m-none-eabi/release/ant-auxiliary.bin"
    "0x08000000"
]
dependencies = [objcopy]
