# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aux.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'aux.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\taux.proto\"Q\n\x07Request\x12\x1a\n\x03\x66\x61n\x18\x01 \x01(\x0b\x32\x0b.FanRequestH\x00\x12\x1c\n\x04temp\x18\x02 \x01(\x0b\x32\x0c.TempRequestH\x00\x42\x0c\n\nperipheral\"s\n\nFanRequest\x12\x1e\n\x03get\x18\x01 \x01(\x0b\x32\x0f.FanRequest.GetH\x00\x12\x1e\n\x03set\x18\x02 \x01(\x0b\x32\x0f.FanRequest.SetH\x00\x1a\x13\n\x03Set\x12\x0c\n\x04\x64uty\x18\x01 \x01(\x05\x1a\x05\n\x03GetB\t\n\x07\x63ommand\"@\n\x0bTempRequest\x12\x1f\n\x03get\x18\x01 \x01(\x0b\x32\x10.TempRequest.GetH\x00\x1a\x05\n\x03GetB\t\n\x07\x63ommand\"(\n\x0b\x46\x61nResponse\x12\x0c\n\x04\x64uty\x18\x01 \x01(\x05\x12\x0b\n\x03rpm\x18\x02 \x01(\x05\"\x0e\n\x0cTempResponse\"T\n\x08Response\x12\x1b\n\x03\x66\x61n\x18\x01 \x01(\x0b\x32\x0c.FanResponseH\x00\x12\x1d\n\x04temp\x18\x02 \x01(\x0b\x32\r.TempResponseH\x00\x42\x0c\n\nperipheralb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aux_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=13
  _globals['_REQUEST']._serialized_end=94
  _globals['_FANREQUEST']._serialized_start=96
  _globals['_FANREQUEST']._serialized_end=211
  _globals['_FANREQUEST_SET']._serialized_start=174
  _globals['_FANREQUEST_SET']._serialized_end=193
  _globals['_FANREQUEST_GET']._serialized_start=195
  _globals['_FANREQUEST_GET']._serialized_end=200
  _globals['_TEMPREQUEST']._serialized_start=213
  _globals['_TEMPREQUEST']._serialized_end=277
  _globals['_TEMPREQUEST_GET']._serialized_start=195
  _globals['_TEMPREQUEST_GET']._serialized_end=200
  _globals['_FANRESPONSE']._serialized_start=279
  _globals['_FANRESPONSE']._serialized_end=319
  _globals['_TEMPRESPONSE']._serialized_start=321
  _globals['_TEMPRESPONSE']._serialized_end=335
  _globals['_RESPONSE']._serialized_start=337
  _globals['_RESPONSE']._serialized_end=421
# @@protoc_insertion_point(module_scope)
